// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Categorie documents
 */
interface CategoryDocumentData {
  /**
   * Titre field in *Categorie*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Afficher dans le menu field in *Categorie*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: category.show_menu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_menu: prismic.BooleanField;

  /**
   * Ordre d'affichage menu field in *Categorie*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: category.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;
}

/**
 * Categorie document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ContactFormSlice
  | OurStoryPageSlice
  | MenuSlice
  | TextImageSlice
  | CarouselSlice
  | HeroHeaderSlice
  | InfoSectionSlice
  | HeroTitleSlice
  | FeatureHighlightSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title_seo
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  title_seo: prismic.KeyTextField;

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description_seo
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_seo: prismic.KeyTextField;

  /**
   * Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.image_seo
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_seo: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Produit → Élements*
 */
export interface ProductDocumentDataItemsItem {
  /**
   * Text field in *Produit → Élements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Content for Produit documents
 */
interface ProductDocumentData {
  /**
   * Image field in *Produit*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Nom field in *Produit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Produit*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Élements field in *Produit*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<ProductDocumentDataItemsItem>>;

  /**
   * Texte CTA field in *Produit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.text_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_cta: prismic.KeyTextField;

  /**
   * Categorie field in *Produit*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: product.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;
}

/**
 * Produit document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

/**
 * Item in *Settings → Réseaux sociaux*
 */
export interface SettingsDocumentDataSocialLinksItem {
  /**
   * Logo field in *Settings → Réseaux sociaux*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Lien field in *Settings → Réseaux sociaux*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo  field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Numéro de téléphone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Mail field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Adresse field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Horaires field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.opening_hours
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  opening_hours: prismic.KeyTextField;

  /**
   * Jours d'ouverture field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.opening_days
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  opening_days: prismic.KeyTextField;

  /**
   * Élements de navigation field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navItems
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navItems: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Lien Click & Collect field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.click_collect_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  click_collect_url: prismic.KeyTextField;

  /**
   * Deliveroo URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.deliveroo_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  deliveroo_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * UberEats URL field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.ubereats_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ubereats_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Réseaux sociaux field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialLinksItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | CategoryDocument
  | PageDocument
  | ProductDocument
  | SettingsDocument;

/**
 * Item in *Carousel → Default → Primary → Produits*
 */
export interface CarouselSliceDefaultPrimaryItemsItem {
  /**
   * Produit field in *Carousel → Default → Primary → Produits*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.items[].produit
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  produit: prismic.ContentRelationshipField<"product">;
}

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Titre field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sous titre field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * CTA field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Voir le menu
   * - **API ID Path**: carousel.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Produits field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<CarouselSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Carousel → Catégorie → Primary*
 */
export interface CarouselSliceCategoryPrimary {
  /**
   * Titre field in *Carousel → Catégorie → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.category.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sous titre field in *Carousel → Catégorie → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.category.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * CTA field in *Carousel → Catégorie → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Voir le menu
   * - **API ID Path**: carousel.category.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Catégorie field in *Carousel → Catégorie → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.category.primary.category
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;
}

/**
 * Catégorie variation for Carousel Slice
 *
 * - **API ID**: `category`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceCategory = prismic.SharedSliceVariation<
  "category",
  Simplify<CarouselSliceCategoryPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault | CarouselSliceCategory;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Item in *FeatureHighlight → Default → Primary → Elements*
 */
export interface FeatureHighlightSliceDefaultPrimaryItemsItem {
  /**
   * Titre field in *FeatureHighlight → Default → Primary → Elements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight.default.primary.items[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Description field in *FeatureHighlight → Default → Primary → Elements*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *FeatureHighlight → Default → Primary*
 */
export interface FeatureHighlightSliceDefaultPrimary {
  /**
   * Titre field in *FeatureHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FeatureHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image étape 1 field in *FeatureHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight.default.primary.step_1_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  step_1_image: prismic.ImageField<never>;

  /**
   * Image étape 2 field in *FeatureHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight.default.primary.step_2_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  step_2_image: prismic.ImageField<never>;

  /**
   * Image étape 3 field in *FeatureHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight.default.primary.step_3_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  step_3_image: prismic.ImageField<never>;

  /**
   * Image étape 4 field in *FeatureHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight.default.primary.step_4_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  step_4_image: prismic.ImageField<never>;

  /**
   * Elements field in *FeatureHighlight → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<FeatureHighlightSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for FeatureHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureHighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureHighlight*
 */
type FeatureHighlightSliceVariation = FeatureHighlightSliceDefault;

/**
 * FeatureHighlight Shared Slice
 *
 * - **API ID**: `feature_highlight`
 * - **Description**: FeatureHighlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureHighlightSlice = prismic.SharedSlice<
  "feature_highlight",
  FeatureHighlightSliceVariation
>;

/**
 * Primary content in *HeroHeader → Default → Primary*
 */
export interface HeroHeaderSliceDefaultPrimary {
  /**
   * Image field in *HeroHeader → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_header.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Titre field in *HeroHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Texte avant CTA field in *HeroHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Compose ta salade
   * - **API ID Path**: hero_header.default.primary.before_cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  before_cta: prismic.KeyTextField;

  /**
   * CTA field in *HeroHeader → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: À emporter
   * - **API ID Path**: hero_header.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for HeroHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroHeader*
 */
type HeroHeaderSliceVariation = HeroHeaderSliceDefault;

/**
 * HeroHeader Shared Slice
 *
 * - **API ID**: `hero_header`
 * - **Description**: HeroHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHeaderSlice = prismic.SharedSlice<
  "hero_header",
  HeroHeaderSliceVariation
>;

/**
 * Primary content in *HeroTitle → Default → Primary*
 */
export interface HeroTitleSliceDefaultPrimary {
  /**
   * Titre field in *HeroTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_title.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *HeroTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_title.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for HeroTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroTitle*
 */
type HeroTitleSliceVariation = HeroTitleSliceDefault;

/**
 * HeroTitle Shared Slice
 *
 * - **API ID**: `hero_title`
 * - **Description**: HeroTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTitleSlice = prismic.SharedSlice<
  "hero_title",
  HeroTitleSliceVariation
>;

/**
 * Item in *InfoSection → Default → Primary → Élements*
 */
export interface InfoSectionSliceDefaultPrimaryItemsItem {
  /**
   * Icone field in *InfoSection → Default → Primary → Élements*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Titre field in *InfoSection → Default → Primary → Élements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *InfoSection → Default → Primary → Élements*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *InfoSection → Default → Primary*
 */
export interface InfoSectionSliceDefaultPrimary {
  /**
   * Titre field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraphe 1 field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.paragraphe_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraphe_1: prismic.KeyTextField;

  /**
   * Paragraphe 2 field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.paragraphe_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraphe_2: prismic.KeyTextField;

  /**
   * CTA field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Élements field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<InfoSectionSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for InfoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InfoSection*
 */
type InfoSectionSliceVariation = InfoSectionSliceDefault;

/**
 * InfoSection Shared Slice
 *
 * - **API ID**: `info_section`
 * - **Description**: InfoSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSectionSlice = prismic.SharedSlice<
  "info_section",
  InfoSectionSliceVariation
>;

/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Menu*
 */
type MenuSliceVariation = MenuSliceDefault;

/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: Menu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSlice = prismic.SharedSlice<"menu", MenuSliceVariation>;

/**
 * Item in *OurStoryPage → Default → Primary → Block Story*
 */
export interface OurStoryPageSliceDefaultPrimaryBlockStoryItem {
  /**
   * Texte field in *OurStoryPage → Default → Primary → Block Story*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story_page.default.primary.block_story[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *OurStoryPage → Default → Primary → Block Story*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story_page.default.primary.block_story[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Titre field in *OurStoryPage → Default → Primary → Block Story*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story_page.default.primary.block_story[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *OurStoryPage → Default → Primary*
 */
export interface OurStoryPageSliceDefaultPrimary {
  /**
   * Hero Image field in *OurStoryPage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story_page.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Titre field in *OurStoryPage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story_page.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Block Story field in *OurStoryPage → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story_page.default.primary.block_story[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  block_story: prismic.GroupField<
    Simplify<OurStoryPageSliceDefaultPrimaryBlockStoryItem>
  >;

  /**
   * Final Text field in *OurStoryPage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story_page.default.primary.final_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  final_text: prismic.KeyTextField;
}

/**
 * Default variation for OurStoryPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurStoryPageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurStoryPageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurStoryPage*
 */
type OurStoryPageSliceVariation = OurStoryPageSliceDefault;

/**
 * OurStoryPage Shared Slice
 *
 * - **API ID**: `our_story_page`
 * - **Description**: OurStoryPage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurStoryPageSlice = prismic.SharedSlice<
  "our_story_page",
  OurStoryPageSliceVariation
>;

/**
 * Primary content in *Slice → Default → Primary*
 */
export interface SliceSliceDefaultPrimary {
  /**
   * text field in *Slice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slice.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * image field in *Slice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slice.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Slice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slice*
 */
type SliceSliceVariation = SliceSliceDefault;

/**
 * Slice Shared Slice
 *
 * - **API ID**: `slice`
 * - **Description**: Slice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliceSlice = prismic.SharedSlice<"slice", SliceSliceVariation>;

/**
 * Primary content in *TextImage → Default → Primary*
 */
export interface TextImageSliceDefaultPrimary {
  /**
   * Titre field in *TextImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sous titre field in *TextImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Description field in *TextImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image à gauche field in *TextImage → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_image.default.primary.image_left
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_left: prismic.BooleanField;

  /**
   * Image field in *TextImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TextImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextImage*
 */
type TextImageSliceVariation = TextImageSliceDefault;

/**
 * TextImage Shared Slice
 *
 * - **API ID**: `text_image`
 * - **Description**: TextImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageSlice = prismic.SharedSlice<
  "text_image",
  TextImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CategoryDocument,
      CategoryDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataItemsItem,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSocialLinksItem,
      AllDocumentTypes,
      CarouselSlice,
      CarouselSliceDefaultPrimaryItemsItem,
      CarouselSliceDefaultPrimary,
      CarouselSliceCategoryPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      CarouselSliceCategory,
      ContactFormSlice,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      FeatureHighlightSlice,
      FeatureHighlightSliceDefaultPrimaryItemsItem,
      FeatureHighlightSliceDefaultPrimary,
      FeatureHighlightSliceVariation,
      FeatureHighlightSliceDefault,
      HeroHeaderSlice,
      HeroHeaderSliceDefaultPrimary,
      HeroHeaderSliceVariation,
      HeroHeaderSliceDefault,
      HeroTitleSlice,
      HeroTitleSliceDefaultPrimary,
      HeroTitleSliceVariation,
      HeroTitleSliceDefault,
      InfoSectionSlice,
      InfoSectionSliceDefaultPrimaryItemsItem,
      InfoSectionSliceDefaultPrimary,
      InfoSectionSliceVariation,
      InfoSectionSliceDefault,
      MenuSlice,
      MenuSliceVariation,
      MenuSliceDefault,
      OurStoryPageSlice,
      OurStoryPageSliceDefaultPrimaryBlockStoryItem,
      OurStoryPageSliceDefaultPrimary,
      OurStoryPageSliceVariation,
      OurStoryPageSliceDefault,
      SliceSlice,
      SliceSliceDefaultPrimary,
      SliceSliceVariation,
      SliceSliceDefault,
      TextImageSlice,
      TextImageSliceDefaultPrimary,
      TextImageSliceVariation,
      TextImageSliceDefault,
    };
  }
}
