// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  carousel: defineAsyncComponent(() => import("./Carousel/index.vue")),
  contact_form: defineAsyncComponent(() => import("./ContactForm/index.vue")),
  feature_highlight: defineAsyncComponent(
    () => import("./FeatureHighlight/index.vue"),
  ),
  hero_header: defineAsyncComponent(() => import("./HeroHeader/index.vue")),
  hero_title: defineAsyncComponent(() => import("./HeroTitle/index.vue")),
  info_section: defineAsyncComponent(() => import("./InfoSection/index.vue")),
  menu: defineAsyncComponent(() => import("./Menu/index.vue")),
  our_story_page: defineAsyncComponent(
    () => import("./OurStoryPage/index.vue"),
  ),
  slice: defineAsyncComponent(() => import("./Slice/index.vue")),
  text_image: defineAsyncComponent(() => import("./TextImage/index.vue")),
});
